## dev环境使用是配置
server:
  port: 8081
  context-path: /chao


spring:
  ## thymeleaf的默认配置
  #spring.thymeleaf.prefix=classpath:/templates/
  #spring.thymeleaf.suffix=.html
  #spring.thymeleaf.mode=HTML5
  #spring.thymeleaf.encoding=UTF-8
  #spring.thymeleaf.content-type=text/html
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    content-type: text/html
    mode: HTML5
    cache: false
  ## freemarker
  #spring.freemarker.allow-request-override=false
  #spring.freemarker.cache=true
  #spring.freemarker.check-template-location=true
  #spring.freemarker.charset=UTF-8
  #spring.freemarker.content-type=text/html
  #spring.freemarker.expose-request-attributes=false
  #spring.freemarker.expose-session-attributes=false
  #spring.freemarker.expose-spring-macro-helpers=false
  freemarker:
    charset: UTF-8
    content-type: text/html
    cache: false
    suffix: .html

  ##数据sql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/manhuaben?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

##必要和@MapperScan(value = "demo.spring.boot.demospringboot.mybatis.dao")一起使用
##一个是dao，一个是mapper
mybatis:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  config-location: classpath:mybatis/config/mybatis-config.xml

resources:
  ##静态资源
  ## -- 如果不配置，都可以访问
  ## -- 如果配置，都可以只能访问指定路径下的
  ## http://localhost:8081/chao/static.txt
  ## http://localhost:8081/chao/public.txt
  static-locations: classpath:/static/

url:
  security:
    ## 拦截需要验证的url,数组的形式
    ## authenticated: /private/**,/framework/**
    authenticated: /private/**







